# Generated by Django 6.0.1 on 2026-01-25 18:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='inventory_name')),
                ('capacity', models.PositiveIntegerField(verbose_name='inventory_capacity')),
                ('location', models.CharField(max_length=50, verbose_name='inventory_location')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='inventory_creation_time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='inventory_last_update_time')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='warehouse_name')),
                ('capacity', models.PositiveIntegerField(verbose_name='warehouse_capacity')),
                ('road', models.CharField(default='N/A', max_length=255, verbose_name='road_location')),
                ('city', models.CharField(default='Dhaka', max_length=255, verbose_name='city_location')),
                ('state', models.CharField(default='Dhaka', max_length=255, verbose_name='state_location')),
                ('country', models.CharField(default='Bangladesh', max_length=255, verbose_name='country_location')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='product_name')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='product_supplier')),
                ('supplier_mail', models.CharField(max_length=255, verbose_name='product_supplier_mail')),
                ('quantity', models.PositiveIntegerField(verbose_name='product_quantity')),
                ('sku', models.CharField(max_length=255, unique=True, verbose_name='product_sku')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product_price')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('Warehouse', 'Warehouse'), ('Inventory', 'Inventory'), ('Product', 'Product')], max_length=50)),
                ('level', models.CharField(choices=[('R', 'Read'), ('C', 'Create'), ('E', 'Edit'), ('D', 'Delete')], max_length=1)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ManyToManyField(related_name='users', to='app.role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_quantity', models.PositiveBigIntegerField()),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_mail', models.CharField(max_length=255)),
                ('supply_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('target_inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.inventory')),
                ('target_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehouse'),
        ),
    ]
