# Generated by Django 6.0.1 on 2026-01-26 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dashboard_category_alter_history_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last update'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(max_length=50, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last_update_time'),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Invited mail')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('E', 'EXPIRED'), ('R', 'REVOKED')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Invited at')),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invites', to=settings.AUTH_USER_MODEL, verbose_name='Invited by')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.role', verbose_name='Given role')),
                ('warehouses', models.ManyToManyField(blank=True, to='app.warehouse', verbose_name='Enrolled Warehouse')),
            ],
            options={
                'verbose_name': 'Invite',
                'verbose_name_plural': 'Invites',
            },
        ),
    ]
