# Generated by Django 6.0.1 on 2026-02-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='email_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
